apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repairagent-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: rook-cephfs-central